apiVersion: v1
kind: ConfigMap
metadata:
  name: epik8s-backend-config
  labels:
    app.kubernetes.io/name: epik8s-backend
    app.kubernetes.io/component: backend
data:
  argocd-url: "https://argocd-server.argocd.svc"
  allowed-origins: "*"
